baseURL : "https://new.cojocaru.co.uk/"
languageCode : "en-gb"
title : "Ionut Cojocaru"

markup:
  defaultMarkdownHandler: "goldmark"

disableKinds:
- taxonomy
- taxonomyTerm

mediaTypes:
  "text/javascript":
    suffixes:
      - "js"